---
# Tasks for deploying Jenkins with Helm
- name: Cordon Kubernetes worker node
  kubernetes.core.k8s_drain:
    name: "{{ k3s_worker_node_name }}"
    state: cordon

- name: Deploy Jenkins
  block:
    - name: Create Jenkins namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ jenkins_namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        state: present

    - name: Create Jenkins persistent volume and storage class
      kubernetes.core.k8s:
        definition: >-
          {{
            lookup(
              'ansible.builtin.file', 
              role_path + '/files/jenkins-01-volume.yaml'
            )
            | from_yaml_all
            | list
          }}
        kubeconfig: "{{ kubeconfig }}"
        state: present

    - name: Create Jenkins service account and RBAC resources
      kubernetes.core.k8s:
        definition: >-
          {{
            lookup(
              'ansible.builtin.file', 
              role_path + '/files/jenkins-02-sa.yaml'
            )
            | from_yaml_all
            | list
          }}
        kubeconfig: "{{ kubeconfig }}"
        state: present

    - name: Add Jenkins Helm repository
      become: false
      kubernetes.core.helm_repository:
        name: jenkins
        repo_url: "{{ jenkins_repo_url }}"
        kubeconfig: "{{ kubeconfig }}"
        state: present

    - name: Install Jenkins
      become: false
      kubernetes.core.helm:
        name: jenkins
        chart_ref: jenkins/jenkins
        release_namespace: "{{ jenkins_namespace }}"
        release_values: >-
          {{
            lookup(
              'ansible.builtin.file',
              role_path + '/files/jenkins-values.yaml'
            )
            | from_yaml
          }}
        kubeconfig: "{{ kubeconfig }}"
        update_repo_cache: true
        wait: true
        wait_timeout: 600
        state: present
      # no_log: true

    - name: Wait for Jenkins pod readiness
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        name: jenkins-0
        namespace: "{{ jenkins_namespace }}"
        kubeconfig: "{{ kubeconfig }}"
        wait: true
        wait_condition:
          type: Ready
          status: "True"
        wait_sleep: 10
        wait_timeout: 300

  always:
    - name: Uncordon Kubernetes worker node
      kubernetes.core.k8s_drain:
        name: "{{ k3s_worker_node_name }}"
        kubeconfig: "{{ kubeconfig }}"
        state: uncordon
