apiVersion: v1
kind: Service
metadata:
  labels:
    app: back-ges-asso
    project: devops
  name: back-ges-asso-service
  namespace: ges-asso
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    app: back-ges-asso
    project: devops
  type: NodePort
